### PR TITLE
💄 Add social networks links

### PR DESCRIPTION
**Pull request by christopherkade**
#26

- Social networks links added to the header
- SVG icons optimized using [svgo](https://github.com/svg/svgo)

Screenshot 2019-04-12 at 16 24 43

### CODE REVIEW

**Comment by frinyvonnick** [comment]
Could you create a component `SocialLinks` so we could move it easier if needed ?

**Comment by frinyvonnick** [comment]
Could you move the component in his own folder called `SocialLinks` with the icons and his css in it ?

**Comment by frinyvonnick** [comment]
Last little change and we are good could you use an index.js in your component folder that export the component so we could change the import in header.js to `import SocialLinks from "../SocialLinks"`. You could find a good article about advantages of doing it in the following link: https://alligator.io/react/index-js-public-interfaces/

**Comment by christopherkade** [comment]
Will do, would that `index` file be directly in the `SocialLinks` folder or would it be at the root of the `components` folder? Having it in the former sounds odd, as it won't contain any other components to export. While having it in the latter would allow us to export every components we produce.

Great tip to know either way, thanks 😄

**Comment by frinyvonnick** [comment]
This `index.js` must be in component folder with the code `export default from './SocialLinks'` so we have more shorter imports without repeating component name twice 😄

**Pull request merged**
