### PR TITLE
:lipstick: Underline link only on mouse over

### LINKED ISSUE #48: Add a hover effect on links
By default links shouldn't be underlined. So the links in resources section should be updated. And all links should be underlined when user pass his mouse over.

### PR DESCRIPTION
**Pull request by ripoul**
Close #48

### CODE REVIEW

**Comment by frinyvonnick** [comment]
@ripoul thanks for your contribution 👍 This change only works for resources section. It should also work for top contributors, top projects and highlighted projects sections. Do you need some pointers about it ?

**Comment by ripoul** [comment]
something like that ?

**Comment by frinyvonnick** [comment]
That's exactly what I expect 👍 but I wonder if you remove `text-decoration: none;` from [People.css](https://github.com/zenika-open-source/insights-website/pull/54/files#diff-8a463753a7dda9deac1dd3a283080f1aR9) and [TopProjects.css](https://github.com/zenika-open-source/insights-website/pull/54/files#diff-9f1708dbc69fb16bee99eb809bb3b75dR7) isn't your global rule sufficient ?

**Comment by ripoul** [comment]
c'est vrai que c'est mieux.

**Comment by frinyvonnick** [comment]
Thank you for your work @ripoul 👍

**Pull request merged**
